default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # Specifies the maximum number of connections that can be opened
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT") { 5000 } %> # in milliseconds. This is how long the app will wait for a database response
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] || 'contentful-sync' %>
  password: <%= ENV["DATABASE_PASSWORD"] || 'contentful-sync' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: contentful-sync_development

test:
  <<: *default
  database: contentful-sync_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: contentful-sync_production # may not be needed, when deploying to heroku
